### ISSUE TITLE
Numeric Variables

### ISSUE THREAD

**Issue by jeromemmiranda** [rowanmanning/varname#4]
It's accepting numeric variables.

| value  | output | expected |
|--------|--------|----------|
| 123var | 123var | var      |
| 1234   | 123    | error    |

**Comment by rowanmanning** [comment]
Hi @jeromemmiranda: it's not clear what functions you're using here. Could you provide more detail? This module doesn't attempt to validate variable names, so numbers are considered OK and it'll just try to do what it thinks is best with them.

**Comment by jeromemmiranda** [comment]
This is a proof that I'm using your plugin for more than 2 years now. Hehe.

But the issue is still there.

Any function actually.

**Comment by rowanmanning** [comment]
Hi @jeromemmiranda, I know this is years later but trying to tidy up this library! The way this library handles numbers is intentional – it's not designed to check that variable names are valid, as this differs language-to-language, it's just designed to split the variable sensibly and string it back together.

[I added a test case which makes this support explicit](https://github.com/rowanmanning/varname/commit/62c427205db511f5f422b6c49cef64b1810bec71). In a future major version I may consider adding in some explicit rules to split numbers. For now if you don't want variable names to start with numbers I think you should manually strip them yourself before passing into this library.

Thanks :)
